name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: dropdown
    id: series
    attributes:
      label: Model Series
      description: |
        What series of Qwen models were you running? 
        Please note that there may not be response for previous model series.
      options:
        - Qwen2
        - Qwen1.5
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: What are the models used?
      description: |
        Please list the model used, e.g., Qwen2-7B-Instruct, Qwen2-72B-Instruct-GGUF, etc.
        Note that we only maintain models at <https://huggingface.co/Qwen> and <https://www.modelscope.com/organization/qwen>.
      placeholder: ex: Qwen2-xxx
    validations:
      required: true
  - type: input
    attributes:
      label: What is the scenario where the problem happened?
      description: | 
        Please briefly describe the scenario, including the type of use and the framework, 
        e.g., inference with `transformers`, deployment with `vllm`, SFT with `llama-factory`, tool calling with `ollama`, etc.
      placeholder: ex: [type of usage] with [framework]
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is this a known issue?
      description: |
        Please first check if you have followed the usage guide in related documentation and if the issue is known: 
        either a workaround is avaiable or the issue has been already reported.
      options:
        - label: I have followed [the GitHub README](https://github.com/QwenLM/Qwen2).
          required: true
        - label: I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
          required: true
        - label: I have checked the documentation of the related framework and cannot find useful information.
          required: true
        - label: I have searched [the issues](https://github.com/QwenLM/Qwen2/issues?q=is%3Aissue) and there is not a similar one.
          required: true
  - type: textarea
    attributes:
      label: Information about environment
      description: |
        Please provide information about you environment, 
        e.g., the software versions and the information on the OS, GPUs, CUDA, and NVIDIA Driver if GPUs are used.
        
        For example:
        - OS: Ubuntu 22.04
        - Python: Python 3.11
        - GPUs: 4 x NVIDIA A20
        - NVIDIA driver: 535 (from `nvidia-smi`)
        - CUDA compiler: 12.1 (from `nvcc -V`)
        - PyTorch: 2.4.1+cu121 (from `python -c "import troch; print(torch.__version__)"`)

        Python packages (from `pip list`)
        ```
        Package                                  Version
        ---------------------------------------- -----------
        accelerate                               0.33.0
        ...
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log output
      description: | 
        Please copy and paste any relevant log output. 
        This will be automatically formatted into code, so no need for backticks. 
        If the log suggested things like
        ```
        RuntimeError: CUDA error: device-side assert triggered
        CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
        For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
        ```
        please follow the instructions and set the corresponding parameters.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe the problem you have encountered.
        The following template is recommended.
        Remember to delete the
      value: |
        #### Steps to reproduce

        This happens to Qwen2-xB-Instruct-xxx and xxx.
        The problem can be reproduced with the following steps:
        1. ...
        2. ...

        #### Expected results

        The results are expected to be ...

        #### Attempts to fix

        I have tried several ways to fix this, including:
        1. ...
        2. ...

        #### Anything else helpful for investigation

        I find that this problem also happens to ... 
    validations:
      required: true
